---
- hosts: install-server
  sudo: true
  vars:
    configure_sh_url: https://raw.githubusercontent.com/enovance/config-tools/automatize_install_server/configure.sh
    puppet_modules:
      hiera:
        url: https://github.com/enovance/puppet-hiera.git
        commit: 1d407be61d800034409e4595a6fb73004b10f70f
      java:
        url: https://github.com/enovance/puppetlabs-java.git
        commit: 5f60d5e2c041848b4c3e71c0aa6ba99b87774d4a
      jenkins:
        url: https://github.com/enovance/puppet-jenkins.git
        commit: 09b8cbc858eb9507009aa56c9895fd126977c9a7
      jenkins_job_builder:
        url: https://github.com/enovance/puppet-jenkins_job_builder.git
        commit: 579939b0e637432fe3e14f297a3af6e6a7ddb1d8
      puppetdb:
        url: https://github.com/enovance/puppetlabs-puppetdb.git
        commit: ed6579b6eaf2c98c8220c41990850949e48b86b4
      cloud:
        url: https://github.com/enovance/puppet-openstack-cloud.git
        commit: automatize_install_server
  tasks:
  - name: Remove current installation of puppet-openstack-cloud
    command: rm -rf /etc/puppet/modules/{{ item.key }}
    with_dict: puppet_modules

  - name: Ensure desired puppet modules are installed
    git: repo={{ item.value.url }}
         version={{ item.value.commit }}
         dest=/etc/puppet/modules/{{ item.key }}
    with_dict: puppet_modules

  - name: Ensure configure.sh is the newest way
    get_url: url={{ configure_sh_url }}
             dest=/usr/bin/
             force=yes
